@echo off
setlocal

rem This sets out an output directory structure as documented in: FolderstructureDetails.docx
echo Running script to create directory structure of installer
SET RELEASEFOLDER=ReleaseInternal
CALL :CREATERELEASEFOLDER

SET RELEASEFOLDER=ReleaseNDA
CALL :CREATERELEASEFOLDER

SET RELEASEFOLDER=ReleasePublic
CALL :CREATERELEASEFOLDER

SET RELEASEFOLDER=ReleaseCommon
CALL :CREATERELEASEFOLDER

GOTO :eof

:CREATERELEASEFOLDER
rem	echo Inside of CREATERELEASEFOLDER
	SET RELEASESUBFOLDER=%RELEASEFOLDER%\32Bit
	if not exist %RELEASESUBFOLDER% (
		CALL :CREATEOSFOLDERS
	)
	SET RELEASESUBFOLDER=%RELEASEFOLDER%\64Bit
	if not exist %RELEASESUBFOLDER% (
		CALL :CREATEOSFOLDERS
	)
	SET RELEASESUBFOLDER=%RELEASEFOLDER%\Common
	if not exist %RELEASESUBFOLDER% (
		CALL :CREATEOSFOLDERS
	)
	SET RELEASESUBFOLDER=%RELEASEFOLDER%\Conditional
	if not exist %RELEASESUBFOLDER% (
		CALL :CREATEOSFOLDERS
	)
	goto :eof

:CREATEOSFOLDERS
rem	echo Inside of CREATEOSFOLDERS
	mkdir  %RELEASESUBFOLDER%\7
	mkdir  %RELEASESUBFOLDER%\2003
	mkdir  %RELEASESUBFOLDER%\2008
	mkdir  %RELEASESUBFOLDER%\All
	mkdir  %RELEASESUBFOLDER%\Vista
	mkdir  %RELEASESUBFOLDER%\XP
	goto :eof
