typedef void* DBHandler;
typedef void* ChunkConfig;
typedef void (*DBReadProgress)(const int, const char*);
void*   open_rocpd_database(const char*);
int     read_trace_properties(DBHandler, DBReadProgress);
int     close_rocpd_database(DBHandler);
int     read_trace_chunk_track_by_track(DBHandler, DBReadProgress);
int     read_trace_chunk_all_tracks(DBHandler db, DBReadProgress);
void    configure_trace_read_time_period(DBHandler, unsigned long long, unsigned long long);
void    add_track_to_trace_read_config(DBHandler, unsigned short);
