// Copyright Advanced Micro Devices, Inc.
// SPDX-License-Identifier: MIT

#pragma once

#include <stdint.h>
#include "rocprofvis_shared_types.h"

typedef uint32_t rocprofvis_property_t;
typedef struct rocprofvis_handle_t rocprofvis_handle_t;
typedef rocprofvis_handle_t rocprofvis_controller_t;
typedef rocprofvis_handle_t rocprofvis_controller_timeline_t;
typedef rocprofvis_handle_t rocprofvis_controller_view_t;
typedef rocprofvis_handle_t rocprofvis_controller_track_t;
typedef rocprofvis_handle_t rocprofvis_controller_graph_t;
typedef rocprofvis_handle_t rocprofvis_controller_table_t;
typedef rocprofvis_handle_t rocprofvis_controller_sample_t;
typedef rocprofvis_handle_t rocprofvis_controller_event_t;
typedef rocprofvis_handle_t rocprofvis_controller_flow_control_t;
typedef rocprofvis_handle_t rocprofvis_controller_callstack_t;
typedef rocprofvis_handle_t rocprofvis_controller_ext_data_t;
typedef rocprofvis_handle_t rocprofvis_controller_future_t;
typedef rocprofvis_handle_t rocprofvis_controller_array_t;
typedef rocprofvis_handle_t rocprofvis_controller_arguments_t;
typedef rocprofvis_handle_t rocprofvis_controller_node_t;
typedef rocprofvis_handle_t rocprofvis_controller_processor_t;
typedef rocprofvis_handle_t rocprofvis_controller_process_t;
typedef rocprofvis_handle_t rocprofvis_controller_plot_t;
typedef rocprofvis_handle_t rocprofvis_controller_thread_t;
typedef rocprofvis_handle_t rocprofvis_controller_queue_t;
typedef rocprofvis_handle_t rocprofvis_controller_stream_t;
typedef rocprofvis_handle_t rocprofvis_controller_counter_t;
typedef rocprofvis_handle_t rocprofvis_controller_summary_t;
typedef rocprofvis_handle_t rocprofvis_controller_summary_metrics_t;
typedef rocprofvis_handle_t rocprofvis_controller_topology_node_t;
#ifdef COMPUTE_UI_SUPPORT
typedef rocprofvis_handle_t rocprofvis_controller_workload_t;
typedef rocprofvis_handle_t rocprofvis_controller_kernel_t;
typedef rocprofvis_handle_t rocprofvis_controller_metrics_container_t;
#endif
