// Copyright Advanced Micro Devices, Inc.
// SPDX-License-Identifier: MIT

#pragma once

#include "rocprofvis_compute_model_types.h"
#include <map>
#include <memory>
#include <unordered_map>

namespace RocProfVis
{
namespace View
{

class ComputeKernelSelectionTable
{
public:
    ComputeKernelSelectionTable();
    ~ComputeKernelSelectionTable() = default;

    const std::vector<std::string>&              GetTableHeader() const;
    const std::vector<std::vector<std::string>>& GetTableData() const;

    const ComputeTableInfo& GetTableInfo() const;
    ComputeTableInfo& GetTableInfoMutable();

    void SetTableInfo(const ComputeTableInfo& info);

    void Clear();

private:
    ComputeTableInfo m_table_info;
};


class ComputeDataModel
{
public:
    using MetricValuesByEntryId = std::map<uint32_t, std::shared_ptr<MetricValue>>;

    ComputeDataModel();
    ~ComputeDataModel() = default;

    const std::unordered_map<uint32_t, WorkloadInfo>& GetWorkloads() const;
    const WorkloadInfo* GetWorkload(uint32_t workload_id) const;
    
    const std::vector<std::shared_ptr<MetricValue>>*  GetMetricsData(uint64_t store_id, uint32_t kernel_id) const;

    void AddWorkload(WorkloadInfo& workload);
    bool AddMetricValue(uint64_t store_id, uint32_t workload_id, uint32_t kernel_id, uint32_t category_id,
                        uint32_t table_id, uint32_t entry_id, std::string& value_name,
                        double value);

    std::shared_ptr<MetricValue> GetMetricValue(uint64_t store_id, uint32_t kernel_id, uint32_t category_id, uint32_t table_id, uint32_t entry_id) const;     
    std::shared_ptr<MetricValue> GetMetricValue(uint64_t store_id, uint32_t kernel_id, uint64_t metric_key) const;

    const AvailableMetrics::Entry* GetMetricInfo(uint32_t workload_id,
                                                 uint32_t category_id, uint32_t table_id,
                                                 uint32_t entry_id) const;

    static const AvailableMetrics::Entry* GetMetricInfo(const WorkloadInfo& workload,
                                                        uint32_t            category_id,
                                                        uint32_t            table_id,
                                                        uint32_t            entry_id);

    MetricValuesByEntryId* GetMetricValuesByTable(uint64_t store_id, uint32_t kernel_id,
                                                  uint32_t category_id,
                                                  uint32_t table_id);
    MetricValuesByEntryId* GetMetricValuesByTable(uint64_t store_id, uint32_t kernel_id,
                                                  uint64_t table_key);

    // Clear entire model (workloads, metrics, tables, etc)
    void Clear();
    // Clear metric values for all stores (clients) and kernels
    void ClearAllMetricValues();
    // Clear metric values for a specific store (client)
    void ClearMetricValues(uint64_t store_id);
    // Clear metric values for a specific store and kernel
    void ClearMetricValues(uint64_t store_id, uint32_t kernel_id);

    ComputeKernelSelectionTable& GetKernelSelectionTable();

    std::vector<const KernelInfo*> GetKernelInfoList(uint32_t workload_id) const;

    const KernelInfo* GetKernelInfo(uint32_t workload_id, uint32_t kernel_id) const;

private:
    std::unordered_map<uint32_t, WorkloadInfo> m_workloads;
    
    struct MetricStore
    {    
        std::vector<std::shared_ptr<MetricValue>>  m_metrics_data;
        
        // Look up map to find metric by id (ex: 2.1.3), key is generated by
        // MetricKey union.
        std::unordered_map<uint64_t, std::shared_ptr<MetricValue>> m_metrics_map;

        // Look up map to find list of metric by table id (ex: 2.1), key is generated by
        // TableKey union.
        std::unordered_map<uint64_t, MetricValuesByEntryId> m_metrics_by_table_id;
    };

    // Map of metrics organized by kernel_id
    using KernelMetricsMap = std::unordered_map<uint32_t, MetricStore>;

    // Map of metrics organized by store_id (client id)
    std::unordered_map<uint64_t, KernelMetricsMap> m_metrics;

    ComputeKernelSelectionTable m_kernel_selection_table;
};

}  // namespace View
}  // namespace RocProfVis
