# Embeds the per-architecture Memory Chart JSON layouts into a generated C++
# header so they are compiled into the binary rather than shipped as runtime
# assets. Mirrors the icon-header codegen pattern used in thirdparty/.
#
# Invoked at build time via `cmake -P` with:
#   -DMEMCHART_DIR=<resources/memory_chart>
#   -DMEMCHART_OUT=<generated header path>
#
# Every "<key>.json" in MEMCHART_DIR (except *schema* files) becomes a string
# literal `kMemChartLayout_<key>` plus a row in `kMemChartEmbeddedLayouts`.
# The runtime picks a layout by GPU-arch key with a "default" fallback.

if(NOT DEFINED MEMCHART_DIR OR NOT DEFINED MEMCHART_OUT)
    message(FATAL_ERROR "embed_memory_chart_layouts: MEMCHART_DIR and MEMCHART_OUT must be set")
endif()

# Raw-string delimiter used for every embedded layout. JSON never contains this
# sequence; we still hard-fail below if it ever does, rather than emit code that
# won't compile.
set(_delim "MCJSON")
set(_close ")${_delim}\"")

file(GLOB _files "${MEMCHART_DIR}/*.json")
list(SORT _files)

set(_body "")
set(_registry "")

foreach(_file ${_files})
    # Skip schema / non-layout helper files (check the FULL name, since NAME_WE
    # strips ".schema.json" entirely and would hide the "schema" marker).
    get_filename_component(_full "${_file}" NAME)
    string(TOLOWER "${_full}" _full_lc)
    if(_full_lc MATCHES "schema")
        continue()
    endif()

    # Layout key = file stem without the trailing ".json" (last extension only).
    get_filename_component(_name "${_file}" NAME_WLE)

    file(READ "${_file}" _content)

    string(FIND "${_content}" "${_close}" _bad_pos)
    if(NOT _bad_pos EQUAL -1)
        message(FATAL_ERROR
            "embed_memory_chart_layouts: '${_file}' contains the raw-string "
            "delimiter '${_close}'. Choose a different delimiter in "
            "cmake/embed_memory_chart_layouts.cmake.")
    endif()

    # C identifier from the file stem (e.g. gfx94x -> gfx94x, "my arch" -> my_arch).
    string(REGEX REPLACE "[^A-Za-z0-9_]" "_" _id "${_name}")

    string(APPEND _body
        "inline constexpr const char* kMemChartLayout_${_id} = R\"${_delim}(\n"
        "${_content}"
        ")${_delim}\";\n\n")
    string(APPEND _registry "    { \"${_name}\", kMemChartLayout_${_id} },\n")
endforeach()

if(_registry STREQUAL "")
    message(FATAL_ERROR "embed_memory_chart_layouts: no layout JSON files found in '${MEMCHART_DIR}'")
endif()

# Assemble with string(APPEND) (single-argument concatenation, no list
# separators) so the emitted C++ is byte-for-byte what we intend.
set(_out "")
string(APPEND _out "// AUTO-GENERATED by cmake/embed_memory_chart_layouts.cmake - DO NOT EDIT.\n")
string(APPEND _out "// Source: resources/memory_chart/*.json\n")
string(APPEND _out "#pragma once\n\n")
string(APPEND _out "namespace RocProfVis\n{\nnamespace View\n{\n\n")
string(APPEND _out "${_body}")
string(APPEND _out "struct MemChartEmbeddedLayout\n{\n")
string(APPEND _out "    const char* key;\n")
string(APPEND _out "    const char* json;\n")
string(APPEND _out "};\n\n")
string(APPEND _out "inline constexpr MemChartEmbeddedLayout kMemChartEmbeddedLayouts[] = {\n")
string(APPEND _out "${_registry}")
string(APPEND _out "};\n\n")
string(APPEND _out "}  // namespace View\n}  // namespace RocProfVis\n")

# Write via a temp + copy_if_different so unchanged content does not bump the
# header's mtime and trigger needless recompiles.
set(_tmp "${MEMCHART_OUT}.tmp")
file(WRITE "${_tmp}" "${_out}")
execute_process(COMMAND "${CMAKE_COMMAND}" -E copy_if_different "${_tmp}" "${MEMCHART_OUT}")
file(REMOVE "${_tmp}")
