# Copyright Advanced Micro Devices, Inc.
# SPDX-License-Identifier: MIT

# Writes the WiX fragment for everything the MSI installs other than
# roc-optiq.exe itself, which wix/roc-optiq.wxs installs and points the
# shortcuts at. The PACKAGE_WIX target installs the runtime component into
# STAGE_DIR and then runs this script before wix build:
#
#   cmake -DSTAGE_DIR=<install tree> -DEXE_NAME=roc-optiq.exe
#         -DOUTPUT=<file.wxs> -P rocprofvis_wix_payload.cmake
#
# The install tree is laid out as INSTALLDIR is, so every file keeps its
# relative path. The fragment defines the RuntimePayload component group,
# empty when there is nothing besides the executable, so roc-optiq.wxs can
# always reference it.

if(NOT STAGE_DIR OR NOT EXE_NAME OR NOT OUTPUT)
    message(FATAL_ERROR "STAGE_DIR, EXE_NAME and OUTPUT are required.")
endif()
if(NOT EXISTS "${STAGE_DIR}/${EXE_NAME}")
    message(FATAL_ERROR "${STAGE_DIR} holds no ${EXE_NAME}; was the runtime component installed?")
endif()

macro(_payload_xml_escape var)
    string(REPLACE "&" "&amp;" ${var} "${${var}}")
    string(REPLACE "<" "&lt;" ${var} "${${var}}")
    string(REPLACE ">" "&gt;" ${var} "${${var}}")
    string(REPLACE "\"" "&quot;" ${var} "${${var}}")
endmacro()

# One component per file, keyed on the file, so Windows Installer tracks and
# removes each one. Ids derive from the install path so they stay stable
# between builds.
file(GLOB_RECURSE _files RELATIVE "${STAGE_DIR}" "${STAGE_DIR}/*")
list(SORT _files)
list(REMOVE_ITEM _files "${EXE_NAME}")

set(_components "")
foreach(_rel IN LISTS _files)
    string(MD5 _id "${_rel}")
    file(TO_NATIVE_PATH "${STAGE_DIR}/${_rel}" _source)
    _payload_xml_escape(_source)
    get_filename_component(_rel_dir "${_rel}" DIRECTORY)
    set(_subdir_attr "")
    if(NOT "${_rel_dir}" STREQUAL "")
        string(REPLACE "/" "\\" _subdir "${_rel_dir}")
        _payload_xml_escape(_subdir)
        set(_subdir_attr " Subdirectory=\"${_subdir}\"")
    endif()
    string(APPEND _components
        "      <Component Id=\"c${_id}\"${_subdir_attr}>\n"
        "        <File Id=\"f${_id}\" Source=\"${_source}\" KeyPath=\"yes\" />\n"
        "      </Component>\n")
endforeach()

list(LENGTH _files _count)
message(STATUS "WiX payload: ${_count} file(s) besides ${EXE_NAME}")

file(WRITE "${OUTPUT}"
    "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
    "<!-- Generated by cmake/rocprofvis_wix_payload.cmake. Do not edit. -->\n"
    "<Wix xmlns=\"http://wixtoolset.org/schemas/v4/wxs\">\n"
    "  <Fragment>\n"
    "    <ComponentGroup Id=\"RuntimePayload\" Directory=\"INSTALLDIR\">\n"
    "${_components}"
    "    </ComponentGroup>\n"
    "  </Fragment>\n"
    "</Wix>\n")
