# Copyright Advanced Micro Devices, Inc.
# SPDX-License-Identifier: MIT

# Writes the WiX fragment for everything the MSI installs beside roc-optiq.exe
# other than the executable itself: the runtime DLLs in the executable's
# directory and, for a vendored scripting build, the Python runtime under
# python\. The PACKAGE_WIX target runs it before wix build:
#
#   cmake -DEXE_DIR=<dir> [-DPYTHON_DIR=<stage>] -DOUTPUT=<file.wxs>
#         -P rocprofvis_wix_payload.cmake
#
# The fragment defines the RuntimePayload component group, empty when there is
# nothing to add, so roc-optiq.wxs can always reference it.

if(NOT EXE_DIR OR NOT OUTPUT)
    message(FATAL_ERROR "EXE_DIR and OUTPUT are required.")
endif()

macro(_payload_xml_escape var)
    string(REPLACE "&" "&amp;" ${var} "${${var}}")
    string(REPLACE "<" "&lt;" ${var} "${${var}}")
    string(REPLACE ">" "&gt;" ${var} "${${var}}")
    string(REPLACE "\"" "&quot;" ${var} "${${var}}")
endmacro()

# One component per file, keyed on the file, so Windows Installer tracks and
# removes each one. Ids derive from the install path so they stay stable
# between builds.
set(_components "")
macro(_payload_add source subdir)
    get_filename_component(_name "${source}" NAME)
    string(MD5 _id "${subdir}/${_name}")
    file(TO_NATIVE_PATH "${source}" _source)
    _payload_xml_escape(_source)
    if("${subdir}" STREQUAL "")
        set(_subdir_attr "")
    else()
        string(REPLACE "/" "\\" _subdir "${subdir}")
        _payload_xml_escape(_subdir)
        set(_subdir_attr " Subdirectory=\"${_subdir}\"")
    endif()
    string(APPEND _components
        "      <Component Id=\"c${_id}\"${_subdir_attr}>\n"
        "        <File Id=\"f${_id}\" Source=\"${_source}\" KeyPath=\"yes\" />\n"
        "      </Component>\n")
endmacro()

file(GLOB _dlls "${EXE_DIR}/*.dll")
list(SORT _dlls)
foreach(_dll IN LISTS _dlls)
    _payload_add("${_dll}" "")
endforeach()

set(_python_count 0)
if(PYTHON_DIR)
    if(NOT IS_DIRECTORY "${PYTHON_DIR}")
        message(FATAL_ERROR "PYTHON_DIR does not exist: ${PYTHON_DIR}")
    endif()
    file(GLOB_RECURSE _python_files RELATIVE "${PYTHON_DIR}" "${PYTHON_DIR}/*")
    list(SORT _python_files)
    list(LENGTH _python_files _python_count)
    foreach(_rel IN LISTS _python_files)
        get_filename_component(_rel_dir "${_rel}" DIRECTORY)
        if("${_rel_dir}" STREQUAL "")
            set(_subdir "python")
        else()
            set(_subdir "python/${_rel_dir}")
        endif()
        _payload_add("${PYTHON_DIR}/${_rel}" "${_subdir}")
    endforeach()
endif()

list(LENGTH _dlls _dll_count)
message(STATUS "WiX payload: ${_dll_count} DLL(s), ${_python_count} Python runtime file(s)")

file(WRITE "${OUTPUT}"
    "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
    "<!-- Generated by cmake/rocprofvis_wix_payload.cmake. Do not edit. -->\n"
    "<Wix xmlns=\"http://wixtoolset.org/schemas/v4/wxs\">\n"
    "  <Fragment>\n"
    "    <ComponentGroup Id=\"RuntimePayload\" Directory=\"INSTALLDIR\">\n"
    "${_components}"
    "    </ComponentGroup>\n"
    "  </Fragment>\n"
    "</Wix>\n")
