name: Continuous Integration Controller
run-name: roc-optiq-ci

on:
  workflow_dispatch:
    inputs:
      upload_to_github:
        description: 'Upload build artifacts to GitHub Artifacts?'
        type: boolean
        default: false
      upload_to_s3:
        description: 'Upload built artifacts to the roc-optiq S3 bucket?'
        type: boolean
        default: false
  schedule:
    - cron: '0 4 * * *'
  push:
    branches:
      - main
    paths-ignore:
      - 'doc/**'
      - '*.md'
  pull_request:
    paths-ignore:
      - 'doc/**'
      - '*.md'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    env:
      # Full OS Coverage (for nightly scheduled builds)
      UBUNTU_FULL_OS_VERSIONS: '[ "22.04", "24.04" ]'
      REDHAT_FULL_OS_VERSIONS: '[ "9", "10" ]'
      WINDOWS_FULL_OS_VERSIONS: '[ "2025" ]'
      # Minimal OS Coverage (for all other builds)
      UBUNTU_CI_OS_VERSIONS: '[ "24.04" ]'
      REDHAT_CI_OS_VERSIONS: '[ "10" ]'
      WINDOWS_CI_OS_VERSIONS: '[ "2025" ]'
    outputs:
      ubuntu-os-versions: ${{ steps.setup-os-versions.outputs.ubuntu-os-versions }}
      redhat-os-versions: ${{ steps.setup-os-versions.outputs.redhat-os-versions }}
      windows-os-versions: ${{ steps.setup-os-versions.outputs.windows-os-versions }}
    steps:
      - name: Set OS versions
        id: setup-os-versions
        run: |
          if [ "${{ github.event_name }}" = "schedule" ]; then
            echo "ubuntu-os-versions=${{ env.UBUNTU_FULL_OS_VERSIONS }}" >> "$GITHUB_OUTPUT"
            echo "redhat-os-versions=${{ env.UBUNTU_FULL_OS_VERSIONS }}" >> "$GITHUB_OUTPUT"
            echo "windows-os-versions=${{ env.WINDOWS_FULL_OS_VERSIONS }}" >> "$GITHUB_OUTPUT"
          else
            echo "ubuntu-os-versions=${{ env.UBUNTU_CI_OS_VERSIONS }}" >> "$GITHUB_OUTPUT"
            echo "redhat-os-versions=${{ env.REDHAT_CI_OS_VERSIONS }}" >> "$GITHUB_OUTPUT"
            echo "windows-os-versions=${{ env.WINDOWS_CI_OS_VERSIONS }}" >> "$GITHUB_OUTPUT"
          fi

  ci-redhat:
    name: RedHat CI
    needs: setup
    uses: ./.github/workflows/ci-redhat.yml
    secrets: inherit
    with:
      os_version: ${{ needs.setup.outputs.redhat-os-versions }}
      upload_to_github: ${{ github.event_name == 'schedule' ||  github.event.inputs.upload_to_github != '' }}
      upload_to_s3: ${{ github.event_name == 'schedule' || github.event.inputs.upload_to_s3 != '' }}

  ci-ubuntu:
    name: Ubuntu CI
    needs: setup
    uses: ./.github/workflows/ci-ubuntu.yml
    secrets: inherit
    with:
      os_version: ${{ needs.setup.outputs.ubuntu-os-versions }}
      upload_to_github: ${{ github.event_name == 'schedule' ||  github.event.inputs.upload_to_github != '' }}
      upload_to_s3: ${{ github.event_name == 'schedule' || github.event.inputs.upload_to_s3 != '' }}

  ci-windows:
    name: Windows CI
    needs: setup
    uses: ./.github/workflows/ci-windows.yml
    secrets: inherit
    with:
      os_version: ${{ needs.setup.outputs.windows-os-versions }}
      upload_to_github: ${{ github.event_name == 'schedule' ||  github.event.inputs.upload_to_github != '' }}
      upload_to_s3: ${{ github.event_name == 'schedule' || github.event.inputs.upload_to_s3 != '' }}
