name: Continuous Integration Controller
run-name: roc-optiq-ci

on:
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * *'
  push:
    branches:
      - main
    paths-ignore:
      - 'doc/**'
      - '*.md'
  pull_request:
    paths-ignore:
      - 'doc/**'
      - '*.md'

env:
  # Full OS Coverage (for nightly scheduled builds)
  UBUNTU_FULL_OS_VERSIONS: '[ "22.04", "24.04" ]'
  REDHAT_FULL_OS_VERSIONS: '[ "9", "10" ]'

  # Minimal OS Coverage (for all other builds)
  UBUNTU_CI_OS_VERSIONS: '[ "24.04" ]'
  REDHAT_CI_OS_VERSIONS: '[ "10" ]'

jobs:
  ci-redhat:
    name: RedHat CI
    uses: ./.github/workflows/ci-redhat.yml
    with:
      os-version: ${{ github.event_name == 'schedule' && env.REDHAT_FULL_OS_VERSIONS || env.REDHAT_CI_OS_VERSIONS }}

  ci-ubuntu:
    name: Ubuntu CI
    uses: ./.github/workflows/ci-ubuntu.yml
    with:
      os-version: ${{ github.event_name == 'schedule' && env.UBUNTU_FULL_OS_VERSIONS || env.UBUNTU_CI_OS_VERSIONS }}

  ci-windows:
    name: Windows CI
    uses: ./.github/workflows/ci-windows.yml
