name: RedHat (Rockylinux) Continuous Integration
run-name: roc-optiq-redhat-ci

on:
  workflow_dispatch:
    inputs:
      os_version:
        description: 'JSON array of OS version(s) to test'
        type: string
        default: '[ "8", "9", "10" ]'
      cmake_config_preset:
        description: 'CMake Config Preset to Use'
        type: string
        default: 'linux-release'
      cmake_build_preset:
        description: 'CMake Build Preset to Use'
        type: string
        default: 'Linux Release Build'
      enable_internal_banner:
        description: 'Enable the internal banner?'
        type: boolean
        default: false
      upload_to_github:
        description: 'Upload build artifacts to GitHub Artifacts?'
        type: boolean
        default: false
      upload_to_s3:
        description: 'Upload built artifacts to the roc-optiq S3 bucket?'
        type: boolean
        default: false
      s3_root_directory:
        description: 'The root directory to use when uploading to the roc-optiq S3 bucket'
        type: choice
        default: 'test'
        options: 
          - test
          - nightly
          - rc
          - release
      release_version:
        description: 'Manually specify a release version to use in the S3 bucket path. Defaults to YYYY_MM_DD timestamp if left empty.'
        type: string
        default: ''
  workflow_call:
    inputs:
      os_version:
        description: 'JSON array of OS version(s) to test'
        type: string
        default: '[ "8", "9", "10" ]'
      cmake_config_preset:
        description: 'CMake Config Preset to Use'
        type: string
        default: 'linux-release'
      cmake_build_preset:
        description: 'CMake Build Preset to Use'
        type: string
        default: 'Linux Release Build'
      enable_internal_banner:
        description: 'Enable the internal banner?'
        type: boolean
        default: false
      upload_to_github:
        description: 'Upload build artifacts to GitHub Artifacts?'
        type: boolean
        default: false
      upload_to_s3:
        description: 'Upload built artifacts to the roc-optiq S3 bucket?'
        type: boolean
        default: false
      s3_root_directory:
        description: 'The root directory to use when uploading to the roc-optiq S3 bucket'
        type: string
        default: 'test'
      release_version:
        description: 'Manually specify a release version to use in the S3 bucket path. Defaults to YYYY_MM_DD timestamp if left empty.'
        type: string
        default: ''

env:
  BUILD_DIR: "build"
  DIST_DIR: "dist"
  BUILD_FILE_NAME: "roc-optiq"
  ENABLE_INTERNAL_BANNER: ${{ inputs.enable_internal_banner == 'true' && 'ON' || 'OFF' }}
  S3_ROOT_DIRECTORY: ${{ inputs.s3_root_directory }}
  RELEASE_VERSION: ${{ inputs.release_version }}

jobs:
  rocky-linux:
    name: RedHat ${{ matrix.os-version }} • Optiq CI • GitHub Artifacts (${{ inputs.upload_to_github }}) • S3 Artifacts (${{ inputs.upload_to_s3 }})
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    permissions:
      id-token: write
      contents: read
    container:
      image: ghcr.io/rocm/optiq-ci-rhel:${{ matrix.os-version }}
    strategy:
      fail-fast: false
      matrix: 
        os-version: ${{ fromJson(inputs.os_version) }}

    steps:
      - uses: actions/checkout@v6
        with:
          lfs: true
          submodules: true

      - name: Build, Make, and Verify Installation
        run: |
          source /opt/vulkan/**/setup-env.sh
          if [ "${{ matrix.os-version }}" = "8" ]; then
            source /opt/rh/gcc-toolset-11/enable
            EXTRA_LINK_FLAGS="-ldl -ltbb"
          else
            EXTRA_LINK_FLAGS=""
          fi
          cmake -B ${{ env.BUILD_DIR }} --preset ${{ inputs.cmake_config_preset }} -DROCPROFVIS_ENABLE_INTERNAL_BANNER=${{ env.ENABLE_INTERNAL_BANNER }} -DGLFW_LINK_STATIC=ON ${EXTRA_LINK_FLAGS:+-DCMAKE_EXE_LINKER_FLAGS="${EXTRA_LINK_FLAGS}"}
          cmake --build ${{ env.BUILD_DIR }} --parallel 4 --target package
          if [ -e build/${{ env.BUILD_FILE_NAME }} ]; then
            echo "✅ ${{ env.BUILD_FILE_NAME }} has been successfully built!"
          else
            echo "❌ ${{ env.BUILD_FILE_NAME }} was not built!"
            exit 1
          fi
      
      - name: Run Tests
        id: run_tests
        continue-on-error: true
        timeout-minutes: 10
        run: |
          cd ${{ env.BUILD_DIR }}
          ctest \
            --output-on-failure \
            --no-tests=error \
            --output-junit ctest-results.xml

      - name: Upload Test Logs (on failure)
        if: steps.run_tests.outcome == 'failure'
        uses: actions/upload-artifact@v7
        with:
          name: test-logs-rhel-${{ matrix.os-version }}
          path: |
            ${{ env.BUILD_DIR }}/ctest-results.xml
            ${{ env.BUILD_DIR }}/Testing/Temporary/**
          retention-days: 7

      - name: Prepare Distribution Artifacts
        run: |
          mkdir ${{ env.DIST_DIR }}
          cp ${{ env.BUILD_DIR }}/${{ env.BUILD_FILE_NAME }} ${{ env.DIST_DIR }}/
          cp ${{ env.BUILD_DIR }}/*.tar.gz ${{ env.DIST_DIR }}/
          cp ${{ env.BUILD_DIR }}/*.rpm ${{ env.DIST_DIR }}/
          ls -l ${{ env.DIST_DIR }}/

      - name: Upload GitHub Artifacts
        if: ${{ inputs.upload_to_github }}
        uses: actions/upload-artifact@v7
        with:
          name: roc-optiq-rhel-${{ matrix.os-version }}-release
          path: |
            ${{ env.DIST_DIR }}/
          retention-days: 2
      
      - name: Configure AWS credentials
        if: ${{ inputs.upload_to_s3 }}
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Generate Metadata for S3
        if: ${{ inputs.upload_to_s3 }}
        working-directory: ${{ env.DIST_DIR }}
        run: |
          createrepo .

      - name: Upload Build to S3
        if: ${{ inputs.upload_to_s3 }}
        run: |
          if [ -z "${{ env.RELEASE_VERSION }}" ]; then
            echo "No release version provided, defaulting to using TIMESTAMP as S3_SECONDARY_DIRECTORY"
            S3_SECONDARY_DIRECTORY=$(date +%Y_%m_%d)
          else
            echo "Release Version ${{ env.RELEASE_VERSION }} provided, using ${{ env.RELEASE_VERSION }} as S3_SECONDARY_DIRECTORY"
            S3_SECONDARY_DIRECTORY="${{ env.RELEASE_VERSION }}"
          fi
          aws s3 cp --recursive ${{ env.DIST_DIR }} s3://${{ secrets.AWS_S3_BUCKET }}/${{ env.S3_ROOT_DIRECTORY }}/$S3_SECONDARY_DIRECTORY/rhel/${{ matrix.os-version }}/ \
            --no-progress

      - name: Announce Test Failure
        if: steps.run_tests.outcome == 'failure'
        run: |
          echo "Tests have failed! Please see uploaded CTest logs for more information"
          exit 1
