name: RedHat (Rockylinux) Continuous Integration
run-name: roc-optiq-redhat-ci

on:
  workflow_call:
    inputs:
      os-version:
        description: 'JSON array of OS version(s) to test'
        required: true
        default: '[ "9", "10" ]'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  BUILD_FILE_NAME: "roc-optiq"

jobs:
  rocky-linux:
    name: RedHat ${{ matrix.os-version }} • Build Optiq
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/rocm/optiq-ci-rhel:${{ matrix.os-version }}
    strategy:
      fail-fast: false
      matrix: 
        os-version: ${{ fromJson(github.event.inputs.os-version) }}

    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true

      - name: Build, Make, and Verify Installation
        shell: bash
        run: |
          source /opt/vulkan/**/setup-env.sh
          cmake -B build --install-prefix /opt/roc-optiq
          cmake --build build --parallel 4
          if [ -e build/${{ env.BUILD_FILE_NAME }} ]; then
            echo "✅ ${{ env.BUILD_FILE_NAME }} has been successfully built!"
          else
            echo "❌ ${{ env.BUILD_FILE_NAME }} was not built!"
            exit 1
          fi
