name: Ubuntu Continuous Integration
run-name: roc-optiq-ubuntu-ci

on:
  workflow_call:
    inputs:
      os-version:
        description: 'JSON array of OS versions to test'
        type: string
        required: true
        default: '[ "22.04", "24.04" ]'

env:
  BUILD_FILE_NAME: "roc-optiq"

jobs:
  ubuntu:
    name: Ubuntu ${{ matrix.os-version }} • Build Optiq
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/rocm/optiq-ci-ubuntu:${{ matrix.os-version }}
    strategy:
      fail-fast: false
      matrix: 
        os-version: ${{ fromJson(inputs.os-version) }}

    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true

      - name: Build, Make, and Verify Installation
        shell: bash
        run: |
          source /opt/vulkan/**/setup-env.sh
          cmake -B build --install-prefix /opt/roc-optiq
          cmake --build build --parallel 4
          if [ -e build/${{ env.BUILD_FILE_NAME }} ]; then
            echo "✅ ${{ env.BUILD_FILE_NAME }} has been successfully built!"
          else
            echo "❌ ${{ env.BUILD_FILE_NAME }} was not built!"
            exit 1
          fi
