name: Release Controller
run-name: roc-optiq-release

on:
  workflow_dispatch:
    inputs:
      dry_run:
        description: 'WARNING: This is enabled by default. Only uncheck this if you are planning on triggering a release!'
        type: boolean
        default: true
      s3_bucket_env:
        description: 'Specify the S3 bucket environment to use for release.'
        type: choice
        default: 'dev'
        options:
          - dev
          - nightly
          - rc
          - stable-staging
      rocm_version:
        description: 'Specify the ROCm version to build with in ManyLinux for release.'
        type: string
        default: '10'

jobs:
  release-manylinux:
    name: ManyLinux Release
    uses: ./.github/workflows/ci-manylinux.yml
    secrets: inherit
    with:
      upload_to_github: ${{ !inputs.dry_run }}
      upload_to_s3: ${{ !inputs.dry_run }}
      s3_bucket_env: ${{ inputs.s3_bucket_env }}
